# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "jekyll", "~> 4.0"
gem "jekyll-feed"
gem "jekyll-remote-theme", github: "benbalter/jekyll-remote-theme"
gem "youtube_rails", github: "luizpicolo/youtube_rails"

group :development do
  gem "webrick", "~> 1.8"
end

